<?php

namespace modava\website\models\table;

use modava\website\models\query\KeyValueQuery;
use Yii;

class KeyValueTable extends \yii\db\ActiveRecord
{
    const STATUS_PUBLISHED = 1;
    const STATUS_DISABLED = 0;

    public static function tableName()
    {
        return 'website_key_value';
    }

    public static function find()
    {
        return new KeyValueQuery(get_called_class());
    }

    public function afterDelete()
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-key-value-get-value-by-key-' . $this->key . '-' . $this->language,
            'redis-key-value-get-id-by-key-' . $this->key . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        $cache = Yii::$app->cache;
        $keys = [
            'redis-key-value-get-value-by-key-' . $this->key . '-' . $this->language,
            'redis-key-value-get-id-by-key-' . $this->key . '-' . $this->language
        ];
        foreach ($keys as $key) {
            $cache->delete($key);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public static function getValueByKey($data_key, $language = null, $data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-key-value-get-value-by-key-' . $data_key . '-' . $language;
        $data = $cache->get($key);
        if ($data == false || $data_cache === false) {
            $query = self::find()->where([self::tableName() . '.key' => $data_key])->published();
            if ($language != null) $query->andWhere([self::tableName() . '.language' => $language]);
            $row = $query->one();

            $data = $row != null ? $row->value : null;

            $cache->set($key, $data);
        }
        return $data;
    }

    public static function getIdByKey($data_key, $language = null, $data_cache = YII2_CACHE)
    {
        $cache = Yii::$app->cache;
        $key = 'redis-key-value-get-id-by-key-' . $data_key . '-' . $language;
        $data = $cache->get($key);
        if ($data == false || $data_cache === false) {
            $query = self::find()->where([self::tableName() . '.key' => $data_key])->published();
            if ($language != null) $query->andWhere([self::tableName() . '.language' => $language]);
            $row = $query->one();

            $data = $row != null ? $row->id : null;

            $cache->set($key, $data);
        }
        return $data;
    }
}