<?php
namespace modava\website\components;

use backend\components\MyController;

class MyWebsiteController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
